title: Sea ice MURI website
description: MURI to study sea ice
author: the MURI team
google_analytics: TEST
author_email: TEST
markdown: kramdown
theme: jekyll-theme-slate
include:
  - index.md
  - people.md
  - particle-model.md
