title: Sea ice MURI website
description: MURI to study sea ice
author: the MURI team
theme: jekyll-theme-slate
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - people.md
  - particle-model.md
